function subplot_pos = getSubplotPos(plots_parameters,col,row)

%{
Input: plots_parameters, column index, row index.
output: position 4 vector of [x0, yo, x_size, y_size];
%}
subplot_pos = [plots_parameters.gapx0 + ...
    (col-1)*(plots_parameters.size_x + plots_parameters.gapx),...
    plots_parameters.gapy0 + ...
    (row-1)*(plots_parameters.size_y + plots_parameters.gapy),...
    plots_parameters.size_x,...
    plots_parameters.size_y];

end