function [] = plotTCR_CD45_pTCR(plots_parameters,Z1,...
    tcr_x,tcr_y,cd45_x,cd45_y,ptcr_x,ptcr_y,alpha)

scatter3(tcr_x,tcr_y,ones(size(tcr_x)),...
    plots_parameters.marker_size,...
    'MarkerEdgeColor','none',...
    'MarkerFaceColor',plots_parameters.tcr.color,...
    'MarkerFaceAlpha',1.0)
hold on
% scatter3(cd45_x,cd45_y,ones(size(cd45_x)),...
%     plots_parameters.marker_size,...
%     'MarkerEdgeColor','none',...
%     'MarkerFaceColor',plots_parameters.cd45.color,...
%     'MarkerFaceAlpha',alpha)

scatter3(ptcr_x,ptcr_y,ones(size(ptcr_x)),...
    plots_parameters.marker_size*1.5,...
    'MarkerEdgeColor','none',...
    'MarkerFaceColor',plots_parameters.ptcr.color,...
    'MarkerFaceAlpha',1.0)

hold off
grid off
box on
view(2)
axis equal
axis tight
f = 0.2;
axis([f*size(Z1,1),...
      (1-f)*size(Z1,1),...
      f*size(Z1,2),...
      (1-f)*size(Z1,2)])

xticks([])
yticks([])
% xticklabels(10*xticks)
% yticklabels(10*yticks)
% colorbar
drawnow

end